Port Prio2 to a VDAF
divviup/libprio-rs pull request #240
Opened 2022-05-27 19:18 UTC by cjpatton

Closes #214.

Defines a new `Vdaf` implementor that wraps the ENPA Prio system into a
VDAF. The implementation is backwards compatible with `Client` and
`Server`.

2022-06-28 21:32 UTC, cjpatton commented on src/vdaf/prio2.rs
> +/// deployed in ENPA for input validation. It also uses a different finite field.
```suggestion
/// The Prio2 VDAF. It supports the same measurement type as
/// [`Prio3Aes128CountVec`](crate::vdaf::prio3::Prio3Aes128CountVec) but uses the proof system
/// and finite field deployed in ENPA.
```

2022-07-07 22:14 UTC, tgeoghegan requested changes

2022-07-07 22:14 UTC, tgeoghegan commented on src/client.rs
>          }
Seems like this check should move down to `ClientMemory::new` since `n` isn't used in this function.

2022-07-07 22:14 UTC, tgeoghegan commented on src/client.rs
> +    pub(crate) fn gen_proof(&mut self, input: &[F]) -> Vec<F> {
I think this would be an opportune moment to add some doccomment explaining just what `input` is and what is returned from this function.

2022-07-07 22:14 UTC, tgeoghegan commented on src/vdaf/prio2.rs
> +        run_vdaf_prepare(&prio2, &verify_key, &(), &nonce, input_shares).expect("test failed");
I believe the `.expect` will discard the error from `run_vdaf_prepare`:

```suggestion
        run_vdaf_prepare(&prio2, &verify_key, &(), &nonce, input_shares).unwrap();
```

2022-07-07 22:47 UTC, tgeoghegan approved these changes
This looks good! Last suggestion would be to gate the `Prio2` VDAF behind a feature but I don't mind including this stuff by default as I don't think it represents a ton of extra code to carry around for clients who want `Prio3`.

2022-07-08 00:23 UTC, cjpatton commented
> This looks good! Last suggestion would be to gate the `Prio2` VDAF behind a feature but I don't mind including this stuff by default as I don't think it represents a ton of extra code to carry around for clients who want `Prio3`.

Done. The new feature is called "prio2".

2022-07-11 16:03 UTC, merged