CI: build benchmarks with all features, yet another clippy fix.
divviup/libprio-rs pull request #249
Opened 2022-06-14 22:18 UTC by BranLwyd

Previously, benchmarks were built with default features only, which
would allow even compilation errors in multithreaded code to pass CI.

Also, run clippy against `--all-features`, and fixup one last clippy
error that this discovered.

2022-06-14 22:23 UTC, divergentdave approved these changes

2022-06-14 22:35 UTC, cjpatton requested changes

2022-06-14 22:35 UTC, cjpatton commented on src/flp/gadgets.rs
> +        for inp in poly_inp.iter_mut() {
Test should pass either way, but you found a bug :) The intention was to test a polynomial for which all of the coefficients are random. Plz fix!

2022-06-15 00:18 UTC, cjpatton approved these changes

2022-06-15 16:00 UTC, merged