field255: Implement `TryFrom<Field255>` for `u64`
divviup/libprio-rs pull request #432
Opened 2023-01-27 22:05 UTC by cjpatton

Based on #431 (merge that first).
Partially addresses #141.

Poplar1 unsharding requires conversion from the leaf field to `u64`.

2023-01-27 22:14 UTC, divergentdave requested changes

2023-01-27 22:14 UTC, divergentdave commented on src/field/field255.rs
> +            is_zero &= !Choice::from(*byte);
This constructor should only be used with `0u8` or `1u8`, changing the "too_big" test to use `[2; 32]` hits a debug assertion inside subtle. Instead, we should use `<u8 as ConstantTimeEq>` methods.

2023-01-27 23:01 UTC, tgeoghegan requested changes

2023-01-27 23:01 UTC, tgeoghegan commented on src/field/field255.rs
> +        for byte in &le_bytes[8..] {
nit: to make it more clear why we're checking that the last 24 bytes are 0, `use std::mem::size_of` and:
```suggestion
        for byte in &le_bytes[size_of::<u64>()..] {
```

2023-01-27 23:59 UTC, cjpatton commented
Rebased.

2023-01-28 00:04 UTC, divergentdave approved these changes

2023-01-28 00:11 UTC, tgeoghegan approved these changes

2023-01-28 00:58 UTC, cjpatton commented
Rebased once more!

2023-01-28 01:31 UTC, merged