poplar1: Partially implement the VDAF
divviup/libprio-rs pull request #434
Opened 2023-01-28 03:21 UTC by cjpatton

Partially addresses #141.

Begin implementing Poplar1. This commit includes the core logic fof the VDAF algorithms, but lacks the serialization code.

2023-01-28 03:22 UTC, cjpatton commented on src/vdaf/poplar1.rs
> +    }));
This is the last bit that's needed before this is ready to review.

2023-02-01 00:47 UTC, tgeoghegan reviewed
Looks sound, I just have a bunch of nits. Also one cross-cutting nits: I'm concerned about the number of TODO comments in here, because it's too easy to lose track of them and either leave them behind after they're addressed, or just never deal with them. I'm especially concerned for those items that require changes to the VDAF spec. Could those TODOs be promoted to issues on this repo or VDAF? Even just one issue with a checklist of items you want to address in subsequent PRs would be nice.

2023-02-01 22:51 UTC, tgeoghegan commented on src/vdaf/poplar1.rs
> +    /// Seed used to generate the Aggregator's share of the randomness used in the first part
If it's incorrect to describe it as the seed for "correlation randomness" in prose, then presumably the field name `corr_seed` is wrong.

2023-02-02 00:21 UTC, cjpatton commented on src/vdaf/poplar1.rs
> +    let mut idpf_eval_cache = RingBufferCache::new(agg_param.prefixes.len());
Yeah I noticed that `NoCache` actulaly seems to perform better. I've left a `TODO(divergentdave)` for you to take a crack at it later :)

A couple of things to keep in mind:
1. We might require in the spec that the candidate prefixes are stored in lexicographic order. (This makes it easier to check for repeats, which is something we know we have to do.) Might that be helpful here?
2. The next PR will have benchmarks to run against.

2023-02-02 00:21 UTC, cjpatton commented on src/vdaf/poplar1.rs
> +        ],
Reviewer note: This value has changed to be more aligned with what I expect to land in VDAF-04. We decided yesterday that we don't need to implement VDAF-03 anyway.

2023-02-02 00:30 UTC, divergentdave commented on src/vdaf/poplar1.rs
> +    let mut idpf_eval_cache = RingBufferCache::new(agg_param.prefixes.len());
I was thinking that if you gave up on caching between different aggregation parameters, and were optimizing for very wide candidate prefix sets, lexicographic order means you could do pretty well with a fixed-size cache of one seed per level.

2023-02-02 00:36 UTC, tgeoghegan commented on src/vdaf/poplar1.rs
> +enum PrepareStateVar {
That works for me.

2023-02-02 00:37 UTC, cjpatton commented on src/vdaf/poplar1.rs
> +    let mut idpf_eval_cache = RingBufferCache::new(agg_param.prefixes.len());
cool, let's give it a try!

2023-02-02 00:38 UTC, tgeoghegan commented on src/vdaf/poplar1.rs
> +    let corr_1 = [x - corr_0[0], y - corr_0[1]]; // B
I think it'd make it easier to map the implementation to the spec and the paper, so it's worth throwing an `#[allow(whatever)]` in.

2023-02-02 00:41 UTC, tgeoghegan requested changes
The change LGTM modulo one or two naming things, but I'd still like to see the TODOs reified into issues per https://github.com/divviup/libprio-rs/pull/434#pullrequestreview-1276192743

2023-02-02 01:32 UTC, cjpatton commented on src/vdaf/poplar1.rs
> +    let mut idpf_eval_cache = RingBufferCache::new(agg_param.prefixes.len());
Moved to https://github.com/divviup/libprio-rs/issues/441.

2023-02-02 01:46 UTC, cjpatton commented on src/vdaf/poplar1.rs
> +    let corr_1 = [x - corr_0[0], y - corr_0[1]]; // B
Done, here and below.

2023-02-02 01:47 UTC, cjpatton commented
> The change LGTM modulo one or two naming things, but I'd still like to see the TODOs reified into issues per [#434 (review)](https://github.com/divviup/libprio-rs/pull/434#pullrequestreview-1276192743)

Which naming things?

Filed:
https://github.com/divviup/libprio-rs/issues/441
https://github.com/divviup/libprio-rs/issues/442

2023-02-02 02:02 UTC, tgeoghegan commented
> Which naming things?
Just `Var -> Variant`, which you already got 

> Filed: #441 #442
> 
> EDIT: I left the "spec TODOs" there because the issues would be filed against cfrg/draft-irtf-cfrg-vdaf.

Yeah, those are the ones that I'm most worried about because they're the least actionable from this project. Any reason not to open some issues on VDAF?

2023-02-02 02:08 UTC, cjpatton commented
> Yeah, those are the ones that I'm most worried about because they're the least actionable from this project. Any reason not to open some issues on VDAF?

https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/134

2023-02-02 16:16 UTC, tgeoghegan approved these changes
Thanks for bearing with me. LGTM!

2023-02-02 18:40 UTC, divergentdave approved these changes

2023-02-02 20:13 UTC, cjpatton commented
Squashed.

2023-02-02 20:23 UTC, merged