Remove ENPA API from public interface, broad refactoring
divviup/libprio-rs pull request #660
Opened 2023-07-26 17:19 UTC by divergentdave

This removes the ENPA API from the crate's public interface, cuts out unneeded code and dependencies, and partly refactors the Prio2 VDAF. Support for encryption of Prio2 shares is removed, which lets us drop dependencies on `ring` and `aes-gcm`. And more:

* Two of the targets in the prio-binaries crate are removed, and the `test-util` feature on the `prio` crate (which supported them) is removed.
* I sorted the dependencies in Cargo.toml and got rid of some comments to make it more maintainable.
* There is still a Prio2 test vector, but I decrypted the input shares and changed its format. There is no longer any code to generate a test vector, as it's served its purpose.
* Prio2 benchmarks are rewritten to use the VDAF API.
* I changed the Prio2/Prio3CountVec comparison part of `vdaf_message_sizes` to output sizes in bytes (like the rest of the output) instead of number of field elements. This was also changed to use the VDAF API.
* The lone integration test was moved to a unit test, allowing us to make the Prio2 test vector struct private, instead of public and hidden from docs.
* Updated doc comments and the README.
* Folded the remnants of the `util` module into other Prio2-related modules, closing #32.
* Replaced ring's SHA256 and HMAC-SHA256 with RustCrypto equivalents in tests and the Prio2 VDAF.
* Removed unused dependencies in prio-binaries and pruned cargo-vet exemptions.

There's more that could be done to remove the `client` and `server` modules entirely, folding them into `src/vdaf/prio2.rs`, moving more methods onto the `Prio2` struct, and rewriting tests that still use `Server`. This PR gets all of that out of the public API, so it'll all be implementation details from here on out.

2023-07-26 21:11 UTC, cjpatton approved these changes
LGTM. One high-level suggestion: I would probably keep around the test vectors for ENPA as they are, with the encryption bits. The reason is to keep a historical record: Someone in the future might want to know how encryption work, and this would give them something that can be easily reproduced for testing.

However that would entail moving the encryption logic into the test code, which has its own cost.

2023-07-26 21:11 UTC, cjpatton commented on src/vdaf/prio2.rs
> +            // Unwrap safety: the constructor checks that this conversion succeeds.
Since we aren't constrained by the old API anymore we might consider propagating this error instead of unwrapping.

2023-07-26 21:29 UTC, divergentdave reviewed
I think the historical purposes would be better served by the commit history and old versions of the crate. Even as test-only code, it would still add to maintenance burden and build times (mainly because of the ring dependency), and it's not worth it if we're not going to use it.

2023-07-26 21:29 UTC, divergentdave commented on README.md
> +details.
Already done :smile:

2023-07-26 23:18 UTC, cjpatton commented
@divergentdave can you resolve the conflicts?

2023-07-27 00:14 UTC, tgeoghegan requested changes

2023-07-27 00:14 UTC, tgeoghegan commented on src/client.rs
Let's move this whole file to `src/vdaf/prio2/client.rs`. I'd like for `prio2` to be just another VDAF and not get the special privilege of having its implementation in the root of the crate.

2023-07-27 00:14 UTC, tgeoghegan commented on src/prng.rs
> +        use sha2::{Digest, Sha256};
nit: hoist these `use`s up to module level

2023-07-27 00:14 UTC, tgeoghegan commented on src/server.rs
As with `src/client.rs`, I'd like to move this to `src/vdaf/prio2/server.rs`.

2023-07-27 00:18 UTC, cjpatton commented on src/client.rs
Would this be a good time to move the sub-modules of `vdaf` into the base crate?

2023-07-27 00:19 UTC, tgeoghegan commented on src/client.rs
Yes and no: we could pile that API break into 0.14.0 with the others, but I'm not sure why we should move the VDAF modules. They're perfectly happy where they are.

2023-07-27 00:29 UTC, cjpatton commented on src/client.rs
Yeah I think I agree. We also have primitives, like `flp` and `idpf`, in the base crate, so it makes sense to keep `vdaf` at the same level. We *could* consider moving `prg` to the base crate for this reason? Not really sure about that one though.

2023-07-27 13:53 UTC, tgeoghegan commented on src/client.rs
I think we could, but not in this PR.

2023-07-27 17:34 UTC, tgeoghegan approved these changes

2023-07-27 18:41 UTC, merged